//! Runtime gRPC helpers used by code generated by `#[toolkit::grpc_contract]`.
//!
//! The wire-level helpers live in [`toolkit_transport_grpc`]: `attach_bearer`,
//! `attach_secctx`, `attach_problem`, `extract_problem`. This module is a
//! thin shim that wraps `attach_bearer` so it produces [`TransportError`]
//! (the macro's `?` chain expects that error type) and provides
//! [`map_tonic_status`] which classifies a `tonic::Status` into the
//! `TransportError` taxonomy used by the rest of the contract runtime.

use tonic::Code;
use tonic::Status;
use tonic::metadata::MetadataMap;
use toolkit_canonical_errors::Problem;

use crate::runtime::transport_error::TransportError;

// Re-export the trait + the inner helper so generated code that references
// `#support::grpc::BearerContext` continues to resolve.
pub use toolkit_transport_grpc::BearerContext;

// `SecurityContextMarker` itself lives in [`crate::grpc_repr`] (always-on)
// so generated code can emit assertions without feature-gating. Provide
// the default impl for `toolkit_security::SecurityContext` here, gated on
// `grpc-client` since that's where the dep enters the build graph.
impl crate::grpc_repr::SecurityContextMarker for toolkit_security::SecurityContext {}

// The platform plane. Unlike the tenant context this one carries no credential —
// it holds a validated `PlatformIdentity`, which is the *result* of inbound
// authentication — so it deliberately does **not** implement `BearerContext`.
// The outbound credential is process-level and is attached at the channel by
// `InternalAuthInterceptor`; the generated client attaches nothing from this
// context. The marker exists so `#[toolkit::grpc_contract]` can assert that a
// parameter it classified as a security context really is one, which is what
// stops a wire DTO named `…SecurityContext` from being silently excluded from the
// payload.
impl crate::grpc_repr::SecurityContextMarker for toolkit_security::PlatformSecurityContext {}

/// Map a [`tonic::Status`] into a [`TransportError`].
///
/// - If the server attached a [`Problem`] payload via the
///   `x-toolkit-problem-bin` binary trailer, surface it as
///   [`TransportError::Problem`].
/// - `Code::Ok` is unexpected here; mapped to [`TransportError::Network`].
/// - Every other code is preserved verbatim as [`TransportError::Grpc`].
///   Retry classification reads the code via [`TransportError::is_transient`];
///   downstream mapping into canonical categories happens in
///   `toolkit-contract::runtime::canonical`.
#[must_use]
pub fn map_tonic_status(status: &Status) -> TransportError {
    match toolkit_transport_grpc::extract_problem::<Problem>(status.metadata()) {
        Ok(Some(problem)) => return TransportError::problem(problem),
        Ok(None) => {}
        Err(problem_decode_err) => {
            tracing::warn!(
                ?problem_decode_err,
                "map_tonic_status: failed to decode problem trailer; falling back to status code",
            );
        }
    }
    let code = status.code();
    if matches!(code, Code::Ok) {
        return TransportError::network("unexpected OK status surfaced as error");
    }
    TransportError::Grpc {
        code,
        message: status.message().to_owned(),
    }
}

/// Attach the bearer token from a security context onto gRPC request
/// metadata. Wraps [`toolkit_transport_grpc::attach_bearer`] so the
/// `tonic::Status` it returns is converted into a [`TransportError`] —
/// keeping the macro's `?` operator chain uniform.
///
/// # Errors
/// Returns a [`TransportError::Grpc`] when the underlying transport-grpc
/// call fails (typically: invalid bytes in the bearer token).
pub fn attach_bearer<C>(metadata: &mut MetadataMap, ctx: &C) -> Result<(), TransportError>
where
    C: BearerContext,
{
    toolkit_transport_grpc::attach_bearer(metadata, ctx).map_err(|s| TransportError::Grpc {
        code: s.code(),
        message: s.message().to_owned(),
    })
}

#[cfg(test)]
#[cfg_attr(coverage_nightly, coverage(off))]
#[allow(clippy::unwrap_used)]
mod tests {
    use super::*;

    #[test]
    fn preserves_unavailable_code_as_transient() {
        let status = Status::unavailable("upstream down");
        let err = map_tonic_status(&status);
        match &err {
            TransportError::Grpc { code, message } => {
                assert_eq!(*code, Code::Unavailable);
                assert_eq!(message, "upstream down");
            }
            other => panic!("unexpected: {other:?}"),
        }
        assert!(err.is_transient());
    }

    #[test]
    fn preserves_deadline_exceeded_code() {
        let status = Status::deadline_exceeded("slow");
        let err = map_tonic_status(&status);
        match &err {
            TransportError::Grpc { code, .. } => assert_eq!(*code, Code::DeadlineExceeded),
            other => panic!("unexpected: {other:?}"),
        }
        assert!(err.is_transient());
    }

    #[test]
    fn preserves_not_found_code() {
        let status = Status::not_found("missing");
        let err = map_tonic_status(&status);
        match err {
            TransportError::Grpc { code, message } => {
                assert_eq!(code, Code::NotFound);
                assert_eq!(message, "missing");
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    #[test]
    fn surfaces_problem_from_binary_trailer() {
        // Build a canonical Problem the same way a server would: from a
        // CanonicalError. The wrapper translates the `tonic::Status` →
        // `TransportError::Problem` so the contract runtime sees a single
        // shape regardless of whether the wire envelope was a Problem
        // trailer or a bare gRPC status.
        let mut metadata = MetadataMap::new();
        let problem = Problem::from(
            toolkit_canonical_errors::CanonicalError::internal(
                "broke \u{1f980} \u{43a}\u{438}\u{440}\u{438}\u{43b}\u{43b}\u{438}\u{446}\u{430}",
            )
            .create(),
        );
        assert_eq!(problem.title, "Internal");
        toolkit_transport_grpc::attach_problem(&mut metadata, &problem).unwrap();
        let mut status = Status::internal("something bad");
        *status.metadata_mut() = metadata;
        match map_tonic_status(&status) {
            TransportError::Problem { problem: p, .. } => {
                assert_eq!(p.title, "Internal");
                assert_eq!(p.status, 500);
                assert!(
                    p.problem_type.contains("internal"),
                    "expected canonical internal GTS URI, got {}",
                    p.problem_type,
                );
            }
            other => panic!("unexpected: {other:?}"),
        }
    }

    /// Verifies the wrapper correctly converts the inner `tonic::Status`
    /// failure into `TransportError::Grpc`. The deeper "did the header
    /// land?" coverage lives in `toolkit-transport-grpc`'s own tests.
    #[test]
    fn attach_bearer_returns_transport_error_on_failure() {
        struct BadBearer;
        impl BearerContext for BadBearer {
            fn bearer_value(&self) -> Option<secrecy::SecretString> {
                // Newline-containing bearer values are rejected by tonic's
                // `MetadataValue::parse`. Forces the error path through
                // the transport-grpc inner helper, which the wrapper must
                // surface as `TransportError::Grpc`.
                Some(secrecy::SecretString::from("invalid\nbearer".to_owned()))
            }
        }
        let mut md = MetadataMap::new();
        let err = attach_bearer(&mut md, &BadBearer).unwrap_err();
        assert!(matches!(err, TransportError::Grpc { .. }));
    }
}
