//! `messages` repository.
//!
//! Owns inserts + active-path reads for the immutable message tree
//! (ADR-0001). The repository is consumed by
//! [`crate::domain::service::message_service::MessageService`] for the
//! `POST /messages/send` pipeline:
//!
//! - [`MessageRepo::insert_user_and_assistant_stub`] runs a single
//!   SERIALIZABLE transaction that derives a fresh `variant_index` for the
//!   user message (via [`crate::infra::db::assign_variant_index`]) and
//!   pre-inserts an assistant stub row (`is_complete=false`) keyed on the
//!   user message ID.
//! - [`MessageRepo::finalize_assistant`] atomically writes the assistant
//!   message's final state (`content`, `is_complete`, `metadata`) once the
//!   plugin stream resolves (success, error, or cancellation).
//! - [`MessageRepo::fetch_active_history`] returns the visible active-path
//!   history the plugin needs to answer the next message — filtering
//!   `is_hidden_from_backend=false AND is_active=true` and ordering by
//!   `created_at ASC`.
//!
//! The trait is object-safe so the service can hold `Arc<dyn MessageRepo>`
//! and unit tests can drop in an in-memory mock. The Sea-ORM impl
//! [`SeaMessageRepo`] is the only place that touches `DatabaseConnection`.
//
// @cpt-cf-chat-engine-message-repo:p5
// @cpt-cf-chat-engine-adr-message-tree-structure:p5

use async_trait::async_trait;
use sea_orm::{
    AccessMode, ActiveModelTrait, ActiveValue::Set, ColumnTrait, DatabaseConnection, EntityTrait,
    IsolationLevel, QueryFilter, QueryOrder, QuerySelect, TransactionError, TransactionTrait,
};
use serde_json::Value as JsonValue;
use time::OffsetDateTime;
use uuid::Uuid;

use crate::domain::error::ChatEngineError;
use crate::domain::message::Message;
use crate::infra::db::assign_variant_index;
use crate::infra::db::entity::message::{self as message_entity, Entity as MessageEntity};

/// Inputs for [`MessageRepo::insert_user_and_assistant_stub`].
#[derive(Debug, Clone)]
pub struct NewUserMessage {
    pub session_id: Uuid,
    /// Parent in the message tree (`None` only for the very first message in
    /// a session). When `Some`, the caller MUST have already verified the
    /// parent belongs to `session_id` via
    /// [`MessageRepo::find_message_in_session`] — the repo only enforces FK
    /// integrity at the DB layer.
    pub parent_message_id: Option<Uuid>,
    /// User-supplied message body (plugin-defined shape; persisted as
    /// JSONB).
    pub content: JsonValue,
    /// Opaque external file UUIDs (Chat Engine never fetches the bytes).
    /// Stored as `Some(json-array)` when non-empty; `None` otherwise.
    pub file_ids: Option<Vec<Uuid>>,
    /// Optional message-level metadata (request_id, capability snapshot, …).
    pub metadata: Option<JsonValue>,
}

/// Outcome of [`MessageRepo::insert_user_and_assistant_stub`] — both IDs are
/// generated by the repo so the caller can immediately reference them in the
/// outgoing NDJSON wire (`StreamingStartEvent { message_id }` uses the
/// assistant id).
#[derive(Debug, Clone, Copy)]
pub struct InsertedPair {
    pub user_message_id: Uuid,
    pub assistant_message_id: Uuid,
    /// `variant_index` assigned to the user message. The assistant stub
    /// always starts at `variant_index=0` because it has no siblings yet
    /// (variants are a recreate-time concern, Phase 6).
    pub user_variant_index: i32,
}

/// Three-way outcome the finalize step must persist. Mirrors the streaming
/// state machine in ADR-0003.
#[derive(Debug, Clone)]
pub enum FinalizeOutcome {
    /// Plugin streamed `Complete` and the response body is ready.
    Complete {
        /// Accumulated assistant text (concatenation of all `Chunk.chunk`
        /// payloads). Stored under `content.text` per the SDK convention.
        text: String,
        /// Plugin-defined metadata (model, finish_reason, usage). When
        /// `Some` it overrides whatever the stub carried.
        metadata: Option<JsonValue>,
    },
    /// Client disconnected (or deadline elapsed) mid-stream. Persist the
    /// partial response with `cancelled=true, partial=true` markers.
    Cancelled {
        /// Accumulated text up to the cancellation point.
        text: String,
    },
    /// Plugin yielded an `Err`/`StreamingErrorEvent` mid-stream. Persist
    /// the partial response with `finish_reason` recorded.
    Errored {
        /// Accumulated text up to the failure point.
        text: String,
        /// Human-readable error message (already trimmed of secrets; safe
        /// to surface to operators).
        error: String,
        /// Canonical finish_reason label (`"error"`, `"timeout"`,
        /// `"interrupted"`). Stored under `metadata.finish_reason`.
        finish_reason: &'static str,
    },
}

/// Repository surface for the `messages` table.
#[async_trait]
pub trait MessageRepo: Send + Sync {
    /// Insert the user message + a pre-allocated assistant stub in a single
    /// SERIALIZABLE transaction.
    ///
    /// - The user message is assigned a fresh `variant_index` via
    ///   [`assign_variant_index`] (Phase 1 helper).
    /// - The assistant stub is created with `parent_message_id = user_id`,
    ///   `is_complete=false`, empty `content`, and `variant_index=0`.
    /// - Returns both IDs and the user `variant_index` so the service can
    ///   reference the assistant id immediately in the outgoing
    ///   `StreamingStartEvent`.
    async fn insert_user_and_assistant_stub(
        &self,
        req: NewUserMessage,
    ) -> Result<InsertedPair, ChatEngineError>;

    /// Atomically finalize the assistant message: updates `content`,
    /// `is_complete`, and `metadata` in one statement.
    ///
    /// Per the Phase 2 contract `messages` has no `updated_at` column;
    /// freshness is conveyed by the `is_complete=true` transition.
    async fn finalize_assistant(
        &self,
        assistant_message_id: Uuid,
        outcome: FinalizeOutcome,
    ) -> Result<(), ChatEngineError>;

    /// Fetch the active visible history for a session, in chronological
    /// order. Filters `is_active=true AND is_hidden_from_backend=false`.
    /// Applies `LIMIT depth` only when `depth.is_some()`.
    async fn fetch_active_history(
        &self,
        session_id: Uuid,
        depth: Option<u32>,
    ) -> Result<Vec<Message>, ChatEngineError>;

    /// Look up a single message scoped to a session — used by the service
    /// to validate `parent_message_id` before any write.
    async fn find_message_in_session(
        &self,
        session_id: Uuid,
        message_id: Uuid,
    ) -> Result<Option<Message>, ChatEngineError>;

    /// Phase 7 hook (context management). Return the *raw* active path for a
    /// session — every message with `is_active=true AND is_complete=true`
    /// ordered by `created_at ASC`. Unlike [`Self::fetch_active_history`],
    /// this method does NOT filter out `is_hidden_from_backend=true` rows:
    /// the [`crate::domain::service::message_service::MessageService::apply_memory_strategy`]
    /// algorithm needs the full active path so it can apply the "keep last K
    /// messages regardless of visibility" rule for the `Summarized`
    /// strategy.
    ///
    /// The default impl delegates to [`Self::fetch_active_history`] so
    /// pre-Phase-7 test mocks keep compiling; the Sea-ORM impl overrides
    /// this with the correct (un-hidden-filtered) query.
    async fn list_active_path(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        self.fetch_active_history(session_id, None).await
    }

    /// Phase 6 hook (recreate). Insert a fresh assistant sibling under
    /// `parent_message_id` with `variant_index = MAX+1`, `is_active=true`,
    /// `is_complete=false`, empty content. The variant index is allocated
    /// via [`assign_variant_index`] (Phase 1 helper).
    ///
    /// Returns an [`InsertedPair`] where `user_message_id = parent_message_id`,
    /// `assistant_message_id = new_row_id`, and `user_variant_index = new_variant_index`.
    ///
    /// Default impl returns `Internal` so existing test mocks compile;
    /// the Sea-ORM impl overrides this.
    async fn insert_assistant_variant_stub(
        &self,
        session_id: Uuid,
        parent_message_id: Uuid,
    ) -> Result<InsertedPair, ChatEngineError> {
        let _ = (session_id, parent_message_id);
        Err(ChatEngineError::internal(
            "insert_assistant_variant_stub not implemented for this repository",
        ))
    }

    /// Phase 8 hook (session intelligence). Persist an AI-generated summary
    /// as a `role=system` message and atomically flip the listed messages'
    /// `is_hidden_from_backend` flag to `true` so future plugin invocations
    /// see the summary in lieu of the originals.
    ///
    /// The summary message has `parent_message_id=NULL`,
    /// `is_hidden_from_user=true`, and `is_complete=true`. The
    /// `summarized_ids` set is applied in the same transaction as the
    /// summary insert, ensuring at-most-once visibility transitions.
    ///
    /// Default impl returns `Internal` so existing test mocks compile;
    /// the SeaORM impl overrides this with a single SERIALIZABLE
    /// transaction.
    async fn insert_summary_message(
        &self,
        session_id: Uuid,
        text: String,
        metadata: Option<JsonValue>,
        summarized_ids: Vec<Uuid>,
    ) -> Result<Uuid, ChatEngineError> {
        let _ = (session_id, text, metadata, summarized_ids);
        Err(ChatEngineError::internal(
            "insert_summary_message not implemented for this repository",
        ))
    }

    /// Phase 8 hook (retention cleanup). List every non-root message
    /// (`parent_message_id IS NOT NULL`) in the session ordered by
    /// `created_at ASC`. Used by the count-based retention algorithm to
    /// pick the oldest messages exceeding the configured threshold.
    ///
    /// Default impl returns an empty list so test mocks that don't care
    /// about retention keep compiling.
    async fn list_non_root_messages_chrono(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let _ = session_id;
        Ok(Vec::new())
    }

    /// Phase 8 hook (retention cleanup). List every non-root message in
    /// the session whose `created_at` is older than `older_than`. Used by
    /// the age-based retention algorithm.
    ///
    /// Default impl returns an empty list so test mocks that don't care
    /// about retention keep compiling.
    async fn list_non_root_messages_older_than(
        &self,
        session_id: Uuid,
        older_than: OffsetDateTime,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let _ = (session_id, older_than);
        Ok(Vec::new())
    }

    /// Phase 8 hook (retention cleanup). Atomically delete the message
    /// identified by `root_id` and every descendant reachable through
    /// `parent_message_id` within `session_id`. The traversal walks the
    /// entire subtree, including hidden / inactive variants, so no
    /// orphans remain.
    ///
    /// Returns the count of rows physically removed (the root plus all
    /// descendants).
    ///
    /// Default impl returns `Internal` so existing test mocks compile;
    /// the SeaORM impl overrides this with a single SERIALIZABLE
    /// transaction wrapping a recursive walk.
    async fn delete_message_subtree(
        &self,
        session_id: Uuid,
        root_id: Uuid,
    ) -> Result<u64, ChatEngineError> {
        let _ = (session_id, root_id);
        Err(ChatEngineError::internal(
            "delete_message_subtree not implemented for this repository",
        ))
    }
}

/// Sea-ORM-backed implementation of [`MessageRepo`].
pub struct SeaMessageRepo {
    db: DatabaseConnection,
}

impl SeaMessageRepo {
    #[must_use]
    pub fn new(db: DatabaseConnection) -> Self {
        Self { db }
    }
}

#[async_trait]
impl MessageRepo for SeaMessageRepo {
    async fn insert_user_and_assistant_stub(
        &self,
        req: NewUserMessage,
    ) -> Result<InsertedPair, ChatEngineError> {
        // Derive the next variant index for the user message in a
        // SERIALIZABLE-bound retry loop. The helper handles the unique-
        // constraint race; the matching INSERT lives in our own
        // transaction below so the two rows land atomically together.
        let user_variant_index =
            assign_variant_index(&self.db, req.session_id, req.parent_message_id).await?;

        let user_message_id = Uuid::new_v4();
        let assistant_message_id = Uuid::new_v4();
        let now = OffsetDateTime::now_utc();

        let file_ids_json = req
            .file_ids
            .as_ref()
            .filter(|ids| !ids.is_empty())
            .and_then(|ids| serde_json::to_value(ids).ok());

        let user_active = message_entity::ActiveModel {
            message_id: Set(user_message_id),
            session_id: Set(req.session_id),
            parent_message_id: Set(req.parent_message_id),
            role: Set("user".to_string()),
            content: Set(req.content),
            file_ids: Set(file_ids_json),
            variant_index: Set(user_variant_index),
            is_active: Set(true),
            is_complete: Set(true),
            is_hidden_from_user: Set(false),
            is_hidden_from_backend: Set(false),
            metadata: Set(req.metadata),
            created_at: Set(now),
        };

        let assistant_active = message_entity::ActiveModel {
            message_id: Set(assistant_message_id),
            session_id: Set(req.session_id),
            parent_message_id: Set(Some(user_message_id)),
            role: Set("assistant".to_string()),
            content: Set(empty_content()),
            file_ids: Set(None),
            variant_index: Set(0),
            is_active: Set(true),
            is_complete: Set(false),
            is_hidden_from_user: Set(false),
            is_hidden_from_backend: Set(false),
            metadata: Set(None),
            created_at: Set(now),
        };

        // Single SERIALIZABLE transaction: either both rows land or neither
        // does. The assistant FK to the user row is implicit (FK is on
        // parent_message_id) — Postgres defers constraint validation to
        // transaction commit so the inserts can be in either order.
        let outcome: Result<(), TransactionError<sea_orm::DbErr>> = self
            .db
            .transaction_with_config::<_, (), sea_orm::DbErr>(
                move |txn| {
                    Box::pin(async move {
                        user_active.insert(txn).await?;
                        assistant_active.insert(txn).await?;
                        Ok(())
                    })
                },
                Some(IsolationLevel::Serializable),
                Some(AccessMode::ReadWrite),
            )
            .await;

        match outcome {
            Ok(()) => Ok(InsertedPair {
                user_message_id,
                assistant_message_id,
                user_variant_index,
            }),
            Err(TransactionError::Transaction(e)) | Err(TransactionError::Connection(e)) => {
                Err(e.into())
            }
        }
    }

    async fn finalize_assistant(
        &self,
        assistant_message_id: Uuid,
        outcome: FinalizeOutcome,
    ) -> Result<(), ChatEngineError> {
        let row = MessageEntity::find_by_id(assistant_message_id)
            .one(&self.db)
            .await?
            .ok_or_else(|| ChatEngineError::not_found("message", assistant_message_id))?;

        let (content, metadata, is_complete) = match outcome {
            FinalizeOutcome::Complete { text, metadata } => {
                (content_with_text(&text), metadata, true)
            }
            FinalizeOutcome::Cancelled { text } => {
                let mut meta = serde_json::Map::new();
                meta.insert("cancelled".into(), JsonValue::Bool(true));
                meta.insert("partial".into(), JsonValue::Bool(true));
                (content_with_text(&text), Some(JsonValue::Object(meta)), false)
            }
            FinalizeOutcome::Errored {
                text,
                error,
                finish_reason,
            } => {
                let mut meta = serde_json::Map::new();
                meta.insert(
                    "finish_reason".into(),
                    JsonValue::String(finish_reason.to_string()),
                );
                meta.insert("error".into(), JsonValue::String(error));
                meta.insert("partial".into(), JsonValue::Bool(true));
                (content_with_text(&text), Some(JsonValue::Object(meta)), false)
            }
        };

        let mut active: message_entity::ActiveModel = row.into();
        active.content = Set(content);
        active.is_complete = Set(is_complete);
        active.metadata = Set(metadata);
        active.update(&self.db).await?;
        Ok(())
    }

    async fn fetch_active_history(
        &self,
        session_id: Uuid,
        depth: Option<u32>,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let mut query = MessageEntity::find()
            .filter(message_entity::Column::SessionId.eq(session_id))
            .filter(message_entity::Column::IsActive.eq(true))
            .filter(message_entity::Column::IsHiddenFromBackend.eq(false))
            // Visible history excludes the assistant stub we're about to
            // fill in (is_complete=false). The stub becomes part of history
            // only on subsequent calls, after `finalize_assistant` flips
            // is_complete to true.
            .filter(message_entity::Column::IsComplete.eq(true))
            .order_by_asc(message_entity::Column::CreatedAt);

        if let Some(d) = depth {
            query = query.limit(u64::from(d));
        }

        let rows = query.all(&self.db).await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn find_message_in_session(
        &self,
        session_id: Uuid,
        message_id: Uuid,
    ) -> Result<Option<Message>, ChatEngineError> {
        let row = MessageEntity::find()
            .filter(message_entity::Column::MessageId.eq(message_id))
            .filter(message_entity::Column::SessionId.eq(session_id))
            .one(&self.db)
            .await?;
        Ok(row.map(Message::from))
    }

    async fn list_active_path(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        // Active-path traversal per the Phase 6 contract: `is_active=true`
        // siblings only, `created_at ASC`. We also require `is_complete=true`
        // so an in-flight assistant stub does not leak into history. Notably
        // we do NOT filter `is_hidden_from_backend` here — the memory
        // strategy may need hidden messages to satisfy the "keep last K"
        // rule.
        let rows = MessageEntity::find()
            .filter(message_entity::Column::SessionId.eq(session_id))
            .filter(message_entity::Column::IsActive.eq(true))
            .filter(message_entity::Column::IsComplete.eq(true))
            .order_by_asc(message_entity::Column::CreatedAt)
            .all(&self.db)
            .await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn list_non_root_messages_chrono(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let rows = MessageEntity::find()
            .filter(message_entity::Column::SessionId.eq(session_id))
            .filter(message_entity::Column::ParentMessageId.is_not_null())
            .order_by_asc(message_entity::Column::CreatedAt)
            .all(&self.db)
            .await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn list_non_root_messages_older_than(
        &self,
        session_id: Uuid,
        older_than: OffsetDateTime,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let rows = MessageEntity::find()
            .filter(message_entity::Column::SessionId.eq(session_id))
            .filter(message_entity::Column::ParentMessageId.is_not_null())
            .filter(message_entity::Column::CreatedAt.lt(older_than))
            .order_by_asc(message_entity::Column::CreatedAt)
            .all(&self.db)
            .await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn insert_summary_message(
        &self,
        session_id: Uuid,
        text: String,
        metadata: Option<JsonValue>,
        summarized_ids: Vec<Uuid>,
    ) -> Result<Uuid, ChatEngineError> {
        let summary_id = Uuid::new_v4();
        let now = OffsetDateTime::now_utc();
        let content = content_with_text(&text);

        let summary_active = message_entity::ActiveModel {
            message_id: Set(summary_id),
            session_id: Set(session_id),
            // Summaries are conversation anchors: persisted at the root
            // level (`parent_message_id = NULL`) so they are excluded from
            // retention cleanup and don't disturb the variant tree.
            parent_message_id: Set(None),
            role: Set("system".to_string()),
            content: Set(content),
            file_ids: Set(None),
            variant_index: Set(0),
            is_active: Set(true),
            is_complete: Set(true),
            // System summaries never surface in the user-facing transcript.
            is_hidden_from_user: Set(true),
            is_hidden_from_backend: Set(false),
            metadata: Set(metadata),
            created_at: Set(now),
        };

        let summarized = summarized_ids.clone();
        let outcome: Result<(), TransactionError<sea_orm::DbErr>> = self
            .db
            .transaction_with_config::<_, (), sea_orm::DbErr>(
                move |txn| {
                    Box::pin(async move {
                        summary_active.insert(txn).await?;
                        if !summarized.is_empty() {
                            MessageEntity::update_many()
                                .col_expr(
                                    message_entity::Column::IsHiddenFromBackend,
                                    sea_orm::sea_query::Expr::value(true),
                                )
                                .filter(message_entity::Column::SessionId.eq(session_id))
                                .filter(
                                    message_entity::Column::MessageId.is_in(summarized.clone()),
                                )
                                .exec(txn)
                                .await?;
                        }
                        Ok(())
                    })
                },
                Some(IsolationLevel::Serializable),
                Some(AccessMode::ReadWrite),
            )
            .await;

        match outcome {
            Ok(()) => Ok(summary_id),
            Err(TransactionError::Transaction(e)) | Err(TransactionError::Connection(e)) => {
                Err(e.into())
            }
        }
    }

    async fn delete_message_subtree(
        &self,
        session_id: Uuid,
        root_id: Uuid,
    ) -> Result<u64, ChatEngineError> {
        // Idempotency: a missing root is a no-op (returns 0). The
        // SERIALIZABLE transaction wraps the recursive walk so concurrent
        // cleanup runs cannot observe partial deletes; the advisory
        // lock acquired by
        // `IntelligenceService::run_retention_cleanup_for_tenant` makes
        // contention unlikely but the repo must remain safe regardless.
        let outcome: Result<u64, TransactionError<sea_orm::DbErr>> = self
            .db
            .transaction_with_config::<_, u64, sea_orm::DbErr>(
                move |txn| {
                    Box::pin(async move {
                        // BFS through `parent_message_id` to collect every
                        // descendant. We accumulate ids first so the
                        // FK-on-parent ordering can be enforced (children
                        // deleted before parents).
                        let mut to_visit: Vec<Uuid> = vec![root_id];
                        let mut ordered: Vec<Uuid> = Vec::new();
                        while let Some(id) = to_visit.pop() {
                            ordered.push(id);
                            let children: Vec<Uuid> = MessageEntity::find()
                                .filter(message_entity::Column::SessionId.eq(session_id))
                                .filter(message_entity::Column::ParentMessageId.eq(id))
                                .all(txn)
                                .await?
                                .into_iter()
                                .map(|m| m.message_id)
                                .collect();
                            to_visit.extend(children);
                        }
                        // Delete leaves-first (reverse traversal order) so
                        // the on_delete=Restrict FK from
                        // `messages.parent_message_id -> messages.message_id`
                        // is satisfied at every step.
                        let mut removed: u64 = 0;
                        for id in ordered.into_iter().rev() {
                            let res = MessageEntity::delete_many()
                                .filter(message_entity::Column::MessageId.eq(id))
                                .filter(message_entity::Column::SessionId.eq(session_id))
                                .exec(txn)
                                .await?;
                            removed += res.rows_affected;
                        }
                        Ok(removed)
                    })
                },
                Some(IsolationLevel::Serializable),
                Some(AccessMode::ReadWrite),
            )
            .await;

        match outcome {
            Ok(n) => Ok(n),
            Err(TransactionError::Transaction(e)) | Err(TransactionError::Connection(e)) => {
                Err(e.into())
            }
        }
    }

    async fn insert_assistant_variant_stub(
        &self,
        session_id: Uuid,
        parent_message_id: Uuid,
    ) -> Result<InsertedPair, ChatEngineError> {
        // Allocate the next variant_index under the same parent via the
        // Phase 1 helper. It internally drives a SERIALIZABLE retry loop
        // capped at VARIANT_INDEX_MAX_RETRIES against
        // `uq_messages_session_parent_variant` collisions.
        let new_variant_index =
            assign_variant_index(&self.db, session_id, Some(parent_message_id)).await?;

        let new_message_id = Uuid::new_v4();
        let now = OffsetDateTime::now_utc();

        let assistant_active = message_entity::ActiveModel {
            message_id: Set(new_message_id),
            session_id: Set(session_id),
            parent_message_id: Set(Some(parent_message_id)),
            role: Set("assistant".to_string()),
            content: Set(empty_content()),
            file_ids: Set(None),
            variant_index: Set(new_variant_index),
            is_active: Set(true),
            is_complete: Set(false),
            is_hidden_from_user: Set(false),
            is_hidden_from_backend: Set(false),
            metadata: Set(None),
            created_at: Set(now),
        };

        let outcome: Result<(), TransactionError<sea_orm::DbErr>> = self
            .db
            .transaction_with_config::<_, (), sea_orm::DbErr>(
                move |txn| {
                    Box::pin(async move {
                        assistant_active.insert(txn).await?;
                        Ok(())
                    })
                },
                Some(IsolationLevel::Serializable),
                Some(AccessMode::ReadWrite),
            )
            .await;

        match outcome {
            Ok(()) => Ok(InsertedPair {
                user_message_id: parent_message_id,
                assistant_message_id: new_message_id,
                user_variant_index: new_variant_index,
            }),
            Err(TransactionError::Transaction(e)) | Err(TransactionError::Connection(e)) => {
                Err(e.into())
            }
        }
    }
}

/// Canonical empty content used for a newly-pre-allocated assistant stub.
/// The SDK stores text under `content.text` (see ADR-0006); on stub creation
/// we persist an empty string so the column is never NULL even before any
/// chunk arrives.
fn empty_content() -> JsonValue {
    serde_json::json!({ "text": "" })
}

/// Build a `content` JSON value with the accumulated text under `text`.
fn content_with_text(text: &str) -> JsonValue {
    serde_json::json!({ "text": text })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn finalize_outcome_complete_carries_metadata() {
        let outcome = FinalizeOutcome::Complete {
            text: "hello".into(),
            metadata: Some(serde_json::json!({"model": "gpt-test"})),
        };
        match outcome {
            FinalizeOutcome::Complete { text, metadata } => {
                assert_eq!(text, "hello");
                assert_eq!(metadata, Some(serde_json::json!({"model": "gpt-test"})));
            }
            other => panic!("expected Complete, got {other:?}"),
        }
    }

    #[test]
    fn empty_content_shape() {
        let v = empty_content();
        assert_eq!(v, serde_json::json!({"text": ""}));
    }

    #[test]
    fn content_with_text_shape() {
        let v = content_with_text("hi");
        assert_eq!(v, serde_json::json!({"text": "hi"}));
    }
}
