//! `messages` repository.
//!
//! Owns inserts + active-path reads for the immutable message tree
//! (ADR-0001). The repository is consumed by
//! [`crate::domain::service::message_service::MessageService`] for the
//! `POST /messages/send` pipeline:
//!
//! - [`MessageRepo::insert_user_and_assistant_stub`] runs a SERIALIZABLE
//!   transaction that computes the next `variant_index` (via
//!   [`crate::infra::db::compute_next_variant_index`]) and inserts the
//!   user message + a matching assistant stub (`is_complete=false`) in
//!   the **same** transaction. The whole pair is retried up to
//!   `VARIANT_INDEX_MAX_RETRIES` times on
//!   `uq_messages_session_parent_variant` collisions so a concurrent
//!   sibling-insert is recovered transparently; exhaustion maps to HTTP
//!   409.
//! - [`MessageRepo::finalize_assistant`] atomically writes the assistant
//!   message's final state (`content`, `is_complete`, `metadata`) once the
//!   plugin stream resolves (success, error, or cancellation).
//! - [`MessageRepo::fetch_active_history`] returns the visible active-path
//!   history the plugin needs to answer the next message — filtering
//!   `is_hidden_from_backend=false AND is_active=true` and ordering by
//!   `created_at ASC`.
//!
//! The trait is object-safe so the service can hold `Arc<dyn MessageRepo>`
//! and unit tests can drop in an in-memory mock. The Sea-ORM impl
//! [`SeaMessageRepo`] threads the toolkit-db `DBProvider` through the same
//! handle the migration runner uses.
//
// @cpt-cf-chat-engine-message-repo:p5
// @cpt-cf-chat-engine-adr-message-tree-structure:p5

use std::sync::Arc;

use async_trait::async_trait;
use toolkit_db::secure::{
    AccessScope, SecureDeleteExt, SecureEntityExt, SecureInsertExt, SecureUpdateExt, TxConfig,
};
use sea_orm::sea_query::Expr;
use sea_orm::{ActiveValue::Set, ColumnTrait, Condition, EntityTrait, QueryOrder};
use serde_json::Value as JsonValue;
use time::OffsetDateTime;
use uuid::Uuid;

use crate::domain::error::ChatEngineError;
use crate::domain::message::Message;
use crate::infra::db::entity::message::{self as message_entity, Entity as MessageEntity};
use crate::infra::db::repo::ChatEngineDb;
use crate::infra::db::{
    VARIANT_INDEX_MAX_RETRIES, compute_next_variant_index, is_variant_unique_violation,
};

/// Inputs for [`MessageRepo::insert_user_and_assistant_stub`].
#[derive(Debug, Clone)]
pub struct NewUserMessage {
    pub session_id: Uuid,
    /// Parent in the message tree (`None` only for the very first message in
    /// a session). When `Some`, the caller MUST have already verified the
    /// parent belongs to `session_id` via
    /// [`MessageRepo::find_message_in_session`] — the repo only enforces FK
    /// integrity at the DB layer.
    pub parent_message_id: Option<Uuid>,
    /// User-supplied message body (plugin-defined shape; persisted as
    /// JSONB).
    pub content: JsonValue,
    /// Opaque external file UUIDs (Chat Engine never fetches the bytes).
    /// Stored as `Some(json-array)` when non-empty; `None` otherwise.
    pub file_ids: Option<Vec<Uuid>>,
    /// Optional message-level metadata (request_id, capability snapshot, …).
    pub metadata: Option<JsonValue>,
}

/// Outcome of [`MessageRepo::insert_user_and_assistant_stub`] — both IDs are
/// generated by the repo so the caller can immediately reference them in the
/// outgoing NDJSON wire (`StreamingStartEvent { message_id }` uses the
/// assistant id).
#[derive(Debug, Clone, Copy)]
pub struct InsertedPair {
    pub user_message_id: Uuid,
    pub assistant_message_id: Uuid,
    /// `variant_index` assigned to the user message. The assistant stub
    /// always starts at `variant_index=0` because it has no siblings yet
    /// (variants are a recreate-time concern, Phase 6).
    pub user_variant_index: i32,
}

/// Three-way outcome the finalize step must persist. Mirrors the streaming
/// state machine in ADR-0003.
#[derive(Debug, Clone)]
pub enum FinalizeOutcome {
    /// Plugin streamed `Complete` and the response body is ready.
    Complete {
        /// Accumulated assistant text (concatenation of all `Chunk.chunk`
        /// payloads). Stored under `content.text` per the SDK convention.
        text: String,
        /// Plugin-defined metadata (model, finish_reason, usage). When
        /// `Some` it overrides whatever the stub carried.
        metadata: Option<JsonValue>,
    },
    /// Client disconnected (or deadline elapsed) mid-stream. Persist the
    /// partial response with `cancelled=true, partial=true` markers.
    Cancelled {
        /// Accumulated text up to the cancellation point.
        text: String,
    },
    /// Plugin yielded an `Err`/`StreamingErrorEvent` mid-stream. Persist
    /// the partial response with `finish_reason` recorded.
    Errored {
        /// Accumulated text up to the failure point.
        text: String,
        /// Human-readable error message (already trimmed of secrets; safe
        /// to surface to operators).
        error: String,
        /// Canonical finish_reason label (`"error"`, `"timeout"`,
        /// `"interrupted"`). Stored under `metadata.finish_reason`.
        finish_reason: &'static str,
    },
}

/// Repository surface for the `messages` table.
#[async_trait]
pub trait MessageRepo: Send + Sync {
    /// Insert the user message + a pre-allocated assistant stub in a single
    /// SERIALIZABLE transaction.
    async fn insert_user_and_assistant_stub(
        &self,
        req: NewUserMessage,
    ) -> Result<InsertedPair, ChatEngineError>;

    /// Atomically finalize the assistant message: updates `content`,
    /// `is_complete`, and `metadata` in one statement.
    async fn finalize_assistant(
        &self,
        session_id: Uuid,
        assistant_message_id: Uuid,
        outcome: FinalizeOutcome,
    ) -> Result<(), ChatEngineError>;

    /// Fetch the active visible history for a session, in chronological
    /// order. Filters `is_active=true AND is_hidden_from_backend=false`.
    /// Applies `LIMIT depth` only when `depth.is_some()`.
    async fn fetch_active_history(
        &self,
        session_id: Uuid,
        depth: Option<u32>,
    ) -> Result<Vec<Message>, ChatEngineError>;

    /// Look up a single message scoped to a session — used by the service
    /// to validate `parent_message_id` before any write.
    async fn find_message_in_session(
        &self,
        session_id: Uuid,
        message_id: Uuid,
    ) -> Result<Option<Message>, ChatEngineError>;

    /// Phase 7 hook (context management). Return the *raw* active path for a
    /// session — every message with `is_active=true AND is_complete=true`
    /// ordered by `created_at ASC`. Unlike [`Self::fetch_active_history`],
    /// this method does NOT filter out `is_hidden_from_backend=true` rows.
    async fn list_active_path(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        self.fetch_active_history(session_id, None).await
    }

    /// Phase 6 hook (recreate). Insert a fresh assistant sibling under
    /// `parent_message_id` with `variant_index = MAX+1`.
    ///
    /// Default impl returns `Internal` so existing test mocks compile;
    /// the Sea-ORM impl overrides this.
    async fn insert_assistant_variant_stub(
        &self,
        session_id: Uuid,
        parent_message_id: Uuid,
    ) -> Result<InsertedPair, ChatEngineError> {
        let _ = (session_id, parent_message_id);
        Err(ChatEngineError::internal(
            "insert_assistant_variant_stub not implemented for this repository",
        ))
    }

    /// Phase 8 hook (session intelligence). Persist an AI-generated summary
    /// as a `role=system` message and atomically flip the listed messages'
    /// `is_hidden_from_backend` flag to `true`.
    async fn insert_summary_message(
        &self,
        session_id: Uuid,
        text: String,
        metadata: Option<JsonValue>,
        summarized_ids: Vec<Uuid>,
    ) -> Result<Uuid, ChatEngineError> {
        let _ = (session_id, text, metadata, summarized_ids);
        Err(ChatEngineError::internal(
            "insert_summary_message not implemented for this repository",
        ))
    }

    /// Phase 8 hook (retention cleanup). List every non-root message in the
    /// session ordered by `created_at ASC`.
    async fn list_non_root_messages_chrono(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let _ = session_id;
        Ok(Vec::new())
    }

    /// Phase 8 hook (retention cleanup). List every non-root message in
    /// the session whose `created_at` is older than `older_than`.
    async fn list_non_root_messages_older_than(
        &self,
        session_id: Uuid,
        older_than: OffsetDateTime,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let _ = (session_id, older_than);
        Ok(Vec::new())
    }

    /// Phase 8 hook (retention cleanup, bounded). Count non-root
    /// messages in the session.
    async fn count_non_root_messages(
        &self,
        session_id: Uuid,
    ) -> Result<u64, ChatEngineError> {
        let _ = session_id;
        Ok(0)
    }

    /// Phase 8 hook (retention cleanup, bounded). Return the IDs of
    /// the OLDEST non-root messages in the session — ordered by
    /// `created_at ASC` — capped at `limit`.
    async fn list_oldest_non_root_message_ids(
        &self,
        session_id: Uuid,
        limit: u32,
    ) -> Result<Vec<Uuid>, ChatEngineError> {
        let _ = (session_id, limit);
        Ok(Vec::new())
    }

    /// Phase 8 hook (retention cleanup, bounded). Return the IDs of
    /// non-root messages with `created_at < older_than`.
    async fn list_non_root_message_ids_older_than(
        &self,
        session_id: Uuid,
        older_than: OffsetDateTime,
        limit: u32,
    ) -> Result<Vec<Uuid>, ChatEngineError> {
        let _ = (session_id, older_than, limit);
        Ok(Vec::new())
    }

    /// Phase 8 hook (retention cleanup). Atomically delete the message
    /// identified by `root_id` and every descendant reachable through
    /// `parent_message_id` within `session_id`.
    async fn delete_message_subtree(
        &self,
        session_id: Uuid,
        root_id: Uuid,
    ) -> Result<u64, ChatEngineError> {
        let _ = (session_id, root_id);
        Err(ChatEngineError::internal(
            "delete_message_subtree not implemented for this repository",
        ))
    }
}

/// Sea-ORM-backed implementation of [`MessageRepo`].
///
/// Holds the toolkit-db `DBProvider` so every query runs against the same
/// connection the migration runner used. `messages` is marked
/// `#[secure(unrestricted)]`; the secure wrappers run with
/// `AccessScope::allow_all()` and exist to expose a `&impl DBRunner`
/// execution path.
pub struct SeaMessageRepo {
    db: Arc<ChatEngineDb>,
}

impl SeaMessageRepo {
    #[must_use]
    pub fn new(db: Arc<ChatEngineDb>) -> Self {
        Self { db }
    }
}

#[async_trait]
impl MessageRepo for SeaMessageRepo {
    async fn insert_user_and_assistant_stub(
        &self,
        req: NewUserMessage,
    ) -> Result<InsertedPair, ChatEngineError> {
        // SERIALIZABLE-bound retry loop that wraps BOTH the
        // `MAX(variant_index)+1` SELECT and the matching INSERT in a
        // single transaction.
        let session_id = req.session_id;
        let parent = req.parent_message_id;
        let file_ids_json = req
            .file_ids
            .as_ref()
            .filter(|ids| !ids.is_empty())
            .and_then(|ids| serde_json::to_value(ids).ok());
        let content = req.content;
        let metadata = req.metadata;

        let mut last_err: Option<ChatEngineError> = None;
        for _attempt in 0..VARIANT_INDEX_MAX_RETRIES {
            let user_message_id = Uuid::new_v4();
            let assistant_message_id = Uuid::new_v4();
            let now = OffsetDateTime::now_utc();
            let content_attempt = content.clone();
            let metadata_attempt = metadata.clone();
            let file_ids_attempt = file_ids_json.clone();

            let outcome: Result<i32, ChatEngineError> = self
                .db
                .transaction_with_config(TxConfig::serializable(), move |tx| {
                    Box::pin(async move {
                        let scope = AccessScope::allow_all();
                        let user_variant_index =
                            compute_next_variant_index(tx, session_id, parent).await?;

                        let user_active = message_entity::ActiveModel {
                            message_id: Set(user_message_id),
                            session_id: Set(session_id),
                            parent_message_id: Set(parent),
                            role: Set(message_entity::MessageRole::User),
                            content: Set(content_attempt),
                            file_ids: Set(file_ids_attempt),
                            variant_index: Set(user_variant_index),
                            is_active: Set(true),
                            is_complete: Set(true),
                            is_hidden_from_user: Set(false),
                            is_hidden_from_backend: Set(false),
                            metadata: Set(metadata_attempt),
                            created_at: Set(now),
                        };
                        let assistant_active = message_entity::ActiveModel {
                            message_id: Set(assistant_message_id),
                            session_id: Set(session_id),
                            parent_message_id: Set(Some(user_message_id)),
                            role: Set(message_entity::MessageRole::Assistant),
                            content: Set(empty_content()),
                            file_ids: Set(None),
                            variant_index: Set(0),
                            is_active: Set(true),
                            is_complete: Set(false),
                            is_hidden_from_user: Set(false),
                            is_hidden_from_backend: Set(false),
                            metadata: Set(None),
                            created_at: Set(now),
                        };
                        MessageEntity::insert(user_active)
                            .secure()
                            .scope_unchecked(&scope)?
                            .exec(tx)
                            .await?;
                        MessageEntity::insert(assistant_active)
                            .secure()
                            .scope_unchecked(&scope)?
                            .exec(tx)
                            .await?;
                        Ok(user_variant_index)
                    })
                })
                .await;

            match outcome {
                Ok(user_variant_index) => {
                    return Ok(InsertedPair {
                        user_message_id,
                        assistant_message_id,
                        user_variant_index,
                    });
                }
                Err(e) => {
                    if let Some(db_err) = chat_engine_db_err(&e) {
                        if !is_variant_unique_violation(db_err) {
                            return Err(e);
                        }
                    } else {
                        return Err(e);
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(retry_exhausted_conflict(last_err))
    }

    async fn finalize_assistant(
        &self,
        session_id: Uuid,
        assistant_message_id: Uuid,
        outcome: FinalizeOutcome,
    ) -> Result<(), ChatEngineError> {
        let (content, metadata, is_complete) = match outcome {
            FinalizeOutcome::Complete { text, metadata } => {
                (content_with_text(&text), metadata, true)
            }
            FinalizeOutcome::Cancelled { text } => {
                let mut meta = serde_json::Map::new();
                meta.insert("cancelled".into(), JsonValue::Bool(true));
                meta.insert("partial".into(), JsonValue::Bool(true));
                (content_with_text(&text), Some(JsonValue::Object(meta)), false)
            }
            FinalizeOutcome::Errored {
                text,
                error,
                finish_reason,
            } => {
                let mut meta = serde_json::Map::new();
                meta.insert(
                    "finish_reason".into(),
                    JsonValue::String(finish_reason.to_string()),
                );
                meta.insert("error".into(), JsonValue::String(error));
                meta.insert("partial".into(), JsonValue::Bool(true));
                (content_with_text(&text), Some(JsonValue::Object(meta)), false)
            }
        };

        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        // Single atomic UPDATE scoped to (message_id, session_id). The
        // `is_complete = false AND metadata IS NULL` predicate matches
        // only the still-pending stub state — any prior finalize leaves
        // the row outside the match set, so a concurrent finalize cannot
        // clobber the winner's terminal state.
        let result = MessageEntity::update_many()
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::MessageId.eq(assistant_message_id))
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::IsComplete.eq(false))
                    .add(message_entity::Column::Metadata.is_null()),
            )
            .col_expr(message_entity::Column::Content, Expr::value(content))
            .col_expr(message_entity::Column::IsComplete, Expr::value(is_complete))
            .col_expr(message_entity::Column::Metadata, Expr::value(metadata))
            .exec(&conn)
            .await?;

        if result.rows_affected == 0 {
            tracing::debug!(
                session_id = %session_id,
                assistant_message_id = %assistant_message_id,
                "finalize_assistant no-op: stub already terminated or not in session",
            );
        }
        Ok(())
    }

    async fn fetch_active_history(
        &self,
        session_id: Uuid,
        depth: Option<u32>,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let mut query = MessageEntity::find()
            .order_by_asc(message_entity::Column::CreatedAt)
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::IsActive.eq(true))
                    .add(message_entity::Column::IsHiddenFromBackend.eq(false))
                    .add(message_entity::Column::IsComplete.eq(true)),
            );

        if let Some(d) = depth {
            query = query.limit(u64::from(d));
        }

        let rows = query.all(&conn).await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn find_message_in_session(
        &self,
        session_id: Uuid,
        message_id: Uuid,
    ) -> Result<Option<Message>, ChatEngineError> {
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let row = MessageEntity::find()
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::MessageId.eq(message_id))
                    .add(message_entity::Column::SessionId.eq(session_id)),
            )
            .one(&conn)
            .await?;
        Ok(row.map(Message::from))
    }

    async fn list_active_path(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        // Active-path traversal per the Phase 6 contract: `is_active=true`
        // siblings only, `created_at ASC`. We also require `is_complete=true`
        // so an in-flight assistant stub does not leak into history. Notably
        // we do NOT filter `is_hidden_from_backend` here — the memory
        // strategy may need hidden messages to satisfy the "keep last K"
        // rule.
        let rows = MessageEntity::find()
            .order_by_asc(message_entity::Column::CreatedAt)
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::IsActive.eq(true))
                    .add(message_entity::Column::IsComplete.eq(true)),
            )
            .all(&conn)
            .await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn list_non_root_messages_chrono(
        &self,
        session_id: Uuid,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let rows = MessageEntity::find()
            .order_by_asc(message_entity::Column::CreatedAt)
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::ParentMessageId.is_not_null()),
            )
            .all(&conn)
            .await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn list_non_root_messages_older_than(
        &self,
        session_id: Uuid,
        older_than: OffsetDateTime,
    ) -> Result<Vec<Message>, ChatEngineError> {
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let rows = MessageEntity::find()
            .order_by_asc(message_entity::Column::CreatedAt)
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::ParentMessageId.is_not_null())
                    .add(message_entity::Column::CreatedAt.lt(older_than)),
            )
            .all(&conn)
            .await?;
        Ok(rows.into_iter().map(Message::from).collect())
    }

    async fn count_non_root_messages(
        &self,
        session_id: Uuid,
    ) -> Result<u64, ChatEngineError> {
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let n = MessageEntity::find()
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::ParentMessageId.is_not_null()),
            )
            .count(&conn)
            .await?;
        Ok(n)
    }

    async fn list_oldest_non_root_message_ids(
        &self,
        session_id: Uuid,
        limit: u32,
    ) -> Result<Vec<Uuid>, ChatEngineError> {
        if limit == 0 {
            return Ok(Vec::new());
        }
        // The secure layer doesn't yet expose `select_only() +
        // into_tuple()`, so we fetch full rows and project in-process.
        // The cost is one extra column per row (the `content` JSONB),
        // bounded by `limit`. Retention runs in batches sized by
        // [`crate::config::ChatEngineConfig::retention_max_deletes_per_session`]
        // so the per-call cap is small (default 100).
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let rows = MessageEntity::find()
            .order_by_asc(message_entity::Column::CreatedAt)
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::ParentMessageId.is_not_null()),
            )
            .limit(u64::from(limit))
            .all(&conn)
            .await?;
        Ok(rows.into_iter().map(|m| m.message_id).collect())
    }

    async fn list_non_root_message_ids_older_than(
        &self,
        session_id: Uuid,
        older_than: OffsetDateTime,
        limit: u32,
    ) -> Result<Vec<Uuid>, ChatEngineError> {
        if limit == 0 {
            return Ok(Vec::new());
        }
        let conn = self.db.conn()?;
        let scope = AccessScope::allow_all();
        let rows = MessageEntity::find()
            .order_by_asc(message_entity::Column::CreatedAt)
            .secure()
            .scope_with(&scope)
            .filter(
                Condition::all()
                    .add(message_entity::Column::SessionId.eq(session_id))
                    .add(message_entity::Column::ParentMessageId.is_not_null())
                    .add(message_entity::Column::CreatedAt.lt(older_than)),
            )
            .limit(u64::from(limit))
            .all(&conn)
            .await?;
        Ok(rows.into_iter().map(|m| m.message_id).collect())
    }

    async fn insert_summary_message(
        &self,
        session_id: Uuid,
        text: String,
        metadata: Option<JsonValue>,
        summarized_ids: Vec<Uuid>,
    ) -> Result<Uuid, ChatEngineError> {
        let summary_id = Uuid::new_v4();
        let now = OffsetDateTime::now_utc();
        let content = content_with_text(&text);

        let summary_active = message_entity::ActiveModel {
            message_id: Set(summary_id),
            session_id: Set(session_id),
            parent_message_id: Set(None),
            role: Set(message_entity::MessageRole::System),
            content: Set(content),
            file_ids: Set(None),
            variant_index: Set(0),
            is_active: Set(true),
            is_complete: Set(true),
            is_hidden_from_user: Set(true),
            is_hidden_from_backend: Set(false),
            metadata: Set(metadata),
            created_at: Set(now),
        };

        let summarized = summarized_ids.clone();
        self.db
            .transaction_with_config(TxConfig::serializable(), move |tx| {
                Box::pin(async move {
                    let scope = AccessScope::allow_all();
                    MessageEntity::insert(summary_active)
                        .secure()
                        .scope_unchecked(&scope)?
                        .exec(tx)
                        .await?;
                    if !summarized.is_empty() {
                        MessageEntity::update_many()
                            .secure()
                            .scope_with(&scope)
                            .filter(
                                Condition::all()
                                    .add(message_entity::Column::SessionId.eq(session_id))
                                    .add(
                                        message_entity::Column::MessageId
                                            .is_in(summarized.clone()),
                                    ),
                            )
                            .col_expr(
                                message_entity::Column::IsHiddenFromBackend,
                                Expr::value(true),
                            )
                            .exec(tx)
                            .await?;
                    }
                    Ok(summary_id)
                })
            })
            .await
    }

    async fn delete_message_subtree(
        &self,
        session_id: Uuid,
        root_id: Uuid,
    ) -> Result<u64, ChatEngineError> {
        // Idempotency: a missing root is a no-op (returns 0). The
        // SERIALIZABLE transaction wraps the walk so concurrent cleanup runs
        // cannot observe partial deletes — keeping it short (O(depth)
        // round-trips, not O(n)) limits serialization-failure / lock
        // contention on the retention hot path.
        self.db
            .transaction_with_config(TxConfig::serializable(), move |tx| {
                Box::pin(async move {
                    let scope = AccessScope::allow_all();
                    // Collect the subtree breadth-first, one
                    // `is_in(frontier)` query per tree level instead of one
                    // `find` per node (mirrors
                    // `SeaVariantRepo::collect_descendants`). `levels[0]` is
                    // the root; deeper levels follow.
                    let mut levels: Vec<Vec<Uuid>> = Vec::new();
                    let mut frontier: Vec<Uuid> = vec![root_id];
                    loop {
                        let children: Vec<Uuid> = MessageEntity::find()
                            .secure()
                            .scope_with(&scope)
                            .filter(
                                Condition::all()
                                    .add(message_entity::Column::SessionId.eq(session_id))
                                    .add(
                                        message_entity::Column::ParentMessageId
                                            .is_in(frontier.clone()),
                                    ),
                            )
                            .all(tx)
                            .await?
                            .into_iter()
                            .map(|m| m.message_id)
                            .collect();
                        levels.push(frontier);
                        if children.is_empty() {
                            break;
                        }
                        frontier = children;
                    }
                    // Delete one whole level per round-trip, deepest first.
                    // A single `is_in(all_ids)` delete is unsafe here: the
                    // `messages.parent_message_id -> messages.message_id` FK
                    // is `on_delete = Restrict`, which is checked immediately
                    // (not deferred to statement end), so a batch that
                    // removed a parent before its child would fail. Sibling
                    // nodes within one level never reference each other, so
                    // each per-level batch is FK-safe once the level below it
                    // is already gone.
                    let mut removed: u64 = 0;
                    for level in levels.into_iter().rev() {
                        let res = MessageEntity::delete_many()
                            .secure()
                            .scope_with(&scope)
                            .filter(
                                Condition::all()
                                    .add(message_entity::Column::SessionId.eq(session_id))
                                    .add(message_entity::Column::MessageId.is_in(level)),
                            )
                            .exec(tx)
                            .await?;
                        removed += res.rows_affected;
                    }
                    Ok(removed)
                })
            })
            .await
    }

    async fn insert_assistant_variant_stub(
        &self,
        session_id: Uuid,
        parent_message_id: Uuid,
    ) -> Result<InsertedPair, ChatEngineError> {
        // Same race-free pattern as `insert_user_and_assistant_stub`:
        // the SELECT for `MAX(variant_index)+1` runs in the SAME
        // SERIALIZABLE transaction as the INSERT.
        let mut last_err: Option<ChatEngineError> = None;
        for _attempt in 0..VARIANT_INDEX_MAX_RETRIES {
            let new_message_id = Uuid::new_v4();
            let now = OffsetDateTime::now_utc();

            let outcome: Result<i32, ChatEngineError> = self
                .db
                .transaction_with_config(TxConfig::serializable(), move |tx| {
                    Box::pin(async move {
                        let scope = AccessScope::allow_all();
                        let new_variant_index = compute_next_variant_index(
                            tx,
                            session_id,
                            Some(parent_message_id),
                        )
                        .await?;
                        let assistant_active = message_entity::ActiveModel {
                            message_id: Set(new_message_id),
                            session_id: Set(session_id),
                            parent_message_id: Set(Some(parent_message_id)),
                            role: Set(message_entity::MessageRole::Assistant),
                            content: Set(empty_content()),
                            file_ids: Set(None),
                            variant_index: Set(new_variant_index),
                            is_active: Set(true),
                            is_complete: Set(false),
                            is_hidden_from_user: Set(false),
                            is_hidden_from_backend: Set(false),
                            metadata: Set(None),
                            created_at: Set(now),
                        };
                        MessageEntity::insert(assistant_active)
                            .secure()
                            .scope_unchecked(&scope)?
                            .exec(tx)
                            .await?;
                        Ok(new_variant_index)
                    })
                })
                .await;

            match outcome {
                Ok(new_variant_index) => {
                    return Ok(InsertedPair {
                        user_message_id: parent_message_id,
                        assistant_message_id: new_message_id,
                        user_variant_index: new_variant_index,
                    });
                }
                Err(e) => {
                    if let Some(db_err) = chat_engine_db_err(&e) {
                        if !is_variant_unique_violation(db_err) {
                            return Err(e);
                        }
                    } else {
                        return Err(e);
                    }
                    last_err = Some(e);
                }
            }
        }
        Err(retry_exhausted_conflict(last_err))
    }
}

/// Reach into a `ChatEngineError` to recover the underlying `sea_orm::DbErr`
/// for retry classification. Only the `Internal { source }` branch carries
/// one; everything else short-circuits the retry.
fn chat_engine_db_err(err: &ChatEngineError) -> Option<&sea_orm::DbErr> {
    let ChatEngineError::Internal { source, .. } = err else {
        return None;
    };
    let source = source.as_ref()?;
    source
        .downcast_ref::<sea_orm::DbErr>()
        .or_else(|| {
            source
                .downcast_ref::<toolkit_db::DbError>()
                .and_then(|dbe| match dbe {
                    toolkit_db::DbError::Sea(inner) => Some(inner),
                    _ => None,
                })
        })
}

/// Map a retry-exhaustion outcome to a `Conflict` ChatEngineError that
/// downstream handlers will render as HTTP 409. The original cause is
/// preserved as the source for log triage.
fn retry_exhausted_conflict(last_err: Option<ChatEngineError>) -> ChatEngineError {
    let base = format!(
        "variant index allocation contended; exhausted {VARIANT_INDEX_MAX_RETRIES} retries"
    );
    ChatEngineError::conflict(match last_err {
        Some(e) => format!("{base}: {e}"),
        None => base,
    })
}

/// Canonical empty content used for a newly-pre-allocated assistant stub.
/// The SDK stores text under `content.text` (see ADR-0006); on stub creation
/// we persist an empty string so the column is never NULL even before any
/// chunk arrives.
fn empty_content() -> JsonValue {
    serde_json::json!({ "text": "" })
}

/// Build a `content` JSON value with the accumulated text under `text`.
fn content_with_text(text: &str) -> JsonValue {
    serde_json::json!({ "text": text })
}
